---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  out.width = "100%"
)
```

# RCGRanges

A minimal R interface to [cgranges](https://github.com/lh3/cgranges) by Heng Li, for fast interval and range queries in genomics.

## Installation

```r
# Install
remotes::install_github("sounkou-bionfo/RCGRanges")
```

## Usage

```{r simple, message=TRUE, warning=TRUE}

library(RCGRanges)

# Create a CGRanges object
gr <- CGRanges()

# Add intervals
grnms <- c("chr1", "chr2")
starts <- c(100L, 200L)
ends <- c(150L, 250L)
labels <- c(1L, 2L)
gr
gr@.ptr

addIntervals(gr, contig_names = grnms, starts = starts, ends = ends, labels = labels)

# Index intervals
gr <- index(gr)
gr
gr@.ptr

# Create second CGRanges object
gr2 <- CGRanges()
addIntervals(gr2, contig_names = c("chr1", "chr2"), starts = c(120L, 210L), ends = c(160L, 260L), labels = c(3L, 4L))
gr2 <- index(gr2)


# Find overlaps between gr and gr2 (indices are 1-based in R)
overlaps <- overlap(gr, gr2)
overlaps_1based <- lapply(overlaps, function(x) lapply(x, function(idx) idx + 1))
print(overlaps_1based)

# Example: non-overlapping intervals
gr3 <- CGRanges()
addIntervals(gr3, contig_names = c("chr1", "chr2"), starts = c(300L, 400L), ends = c(350L, 450L), labels = c(5L, 6L))
gr3 <- index(gr3)
overlaps_none <- overlap(gr, gr3)
overlaps_none_1based <- lapply(overlaps_none, function(x) lapply(x, function(idx) idx + 1))
print(overlaps_none_1based)
```

## Reference

- [cgranges by Heng Li](https://github.com/lh3/cgranges)
